version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  go-api:
    build:
      context: .
    container_name: go-api
    depends_on:
      - postgres
    environment:
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data:
