package main

import hello "go-hello-world/hello"

func main() {
	hello.Hello()
	hello.Values()
	hello.Variables()
	hello.Constants()
	hello.Loops()
	hello.Condition()
	hello.Switch()
	hello.Array()
	hello.Slice()
	hello.Maps()
	hello.Function()
	hello.Range()
	hello.Pointers()
	hello.String()
	hello.StructNew()
	hello.Methods()
	hello.InterfaceFunc()
	hello.Enum()
	hello.StructEmbeddings()
	hello.Errors()
	hello.Goriutines()
	hello.Channels()
	hello.Select()
	hello.Timeout()
	hello.RangeChannel()
	hello.Ticker()
	hello.WorkerPool()
	hello.Sorting()
	hello.Panic()
	hello.UrlParsing()
	hello.HttiCLient()
}
